/*

*/

package synom;

import org.jfree.ui.RefineryUtilities;


public class GUI extends javax.swing.JFrame {

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cpuLoad = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        totalRAM = new javax.swing.JLabel();
        cpuGraph = new javax.swing.JButton();
        ramGraph = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        osLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        cpuLoad.setForeground(new java.awt.Color(0, 255, 102));
        cpuLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpuLoad.setText("CPU");

        ram.setForeground(new java.awt.Color(0, 255, 102));
        ram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ram.setText("RAM");

        totalRAM.setForeground(new java.awt.Color(0, 255, 102));
        totalRAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalRAM.setText("totalRAM");

        cpuGraph.setBackground(new java.awt.Color(102, 102, 102));
        cpuGraph.setForeground(new java.awt.Color(0, 255, 51));
        cpuGraph.setText("CPU Graph");
        cpuGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuGraphActionPerformed(evt);
            }
        });

        ramGraph.setBackground(new java.awt.Color(102, 102, 102));
        ramGraph.setForeground(new java.awt.Color(0, 255, 51));
        ramGraph.setText("RAM Graph");
        ramGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramGraphActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Status");

        osLabel.setForeground(new java.awt.Color(0, 255, 102));
        osLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        osLabel.setText("Operating System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(totalRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpuGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ramGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(osLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cpuLoad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(osLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpuLoad)
                .addGap(18, 18, 18)
                .addComponent(ram)
                .addGap(18, 18, 18)
                .addComponent(totalRAM)
                .addGap(18, 18, 18)
                .addComponent(cpuGraph)
                .addGap(18, 18, 18)
                .addComponent(ramGraph)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpuGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuGraphActionPerformed
        // TODO add your handling code here:        
        Synom.chartCPU.setVisible(true);
        Synom.chartCPU.pack();
        RefineryUtilities.centerFrameOnScreen(Synom.chartCPU);
        Synom.chartCPU.setVisible(true);
        Synom.chartCPU.button.setVisible(false);
        this.cpuGraph.setEnabled(false);
    }//GEN-LAST:event_cpuGraphActionPerformed

    private void ramGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramGraphActionPerformed
        Synom.chartRAM.setVisible(true);
        Synom.chartRAM.pack();
        RefineryUtilities.centerFrameOnScreen(Synom.chartRAM);
        Synom.chartRAM.setVisible(true);
        Synom.chartRAM.button.setVisible(false);
        this.ramGraph.setEnabled(false);
    }//GEN-LAST:event_ramGraphActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cpuGraph;
    public javax.swing.JLabel cpuLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel osLabel;
    public javax.swing.JLabel ram;
    public javax.swing.JButton ramGraph;
    public javax.swing.JLabel totalRAM;
    // End of variables declaration//GEN-END:variables
}
