/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package synom;

/**
 *
 * @author Liviu
 */
public class GUIv2 extends javax.swing.JPanel {

    /**
     * Creates new form GUIv2
     */
    public GUIv2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ram = new javax.swing.JLabel();
        totalRAM = new javax.swing.JLabel();
        cpuLoad = new javax.swing.JLabel();

        ram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ram.setText("RAM");

        totalRAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalRAM.setText("totalRAM");

        cpuLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpuLoad.setText("CPU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cpuLoad)
                .addGap(18, 18, 18)
                .addComponent(ram)
                .addGap(18, 18, 18)
                .addComponent(totalRAM)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cpuLoad;
    public javax.swing.JLabel ram;
    public javax.swing.JLabel totalRAM;
    // End of variables declaration//GEN-END:variables
}
